const movies = [
    {
        id: 1,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/movie/e/i/f/2012-dvd-soni-hindi-the-adventures-of-tintin-the-secret-of-the-original-imagqbtvtakrzg8f.jpeg?q=70",
        title: "THE ADVENTURES OF TINTIN",
        language: "Hindi",
        cost: 200,
    },
    {
        id: 2,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/movie/4/f/r/2009-dvd-eagle-hindi-tarzan-the-wonder-car-original-imahfdpjpqg85j5d.jpeg?q=70",
        title: "TAARZAN THE WONDER CAR ",
        language: "Hindi",
        cost: 249,
    },
    {
        id: 3,
        image: "https://rukminim2.flixcart.com/image/612/612/av-media/movies/2/g/w/gangs-of-wasseypur-i-ii-original-imadnzhpajzajcah.jpeg?q=70",
        title: " Gangs Of Wasseypur I - II",
        language: "Hindi",
        cost: 875,
    },
    {
        id: 4,
        image: "https://rukminim2.flixcart.com/image/612/612/jeokbrk0/movie/z/6/2/2009-dvd-excel-home-videos-english-avatar-original-imaf3bd6zed7phes.jpeg?q=70",
        title: " Avatar",
        language: "Hindi",
        cost: 545,
    },
    {
        id: 5,
        image: "https://rukminim2.flixcart.com/image/612/612/movie/z/v/4/deadpool-2016-english-dvd-excel-home-videos-original-imaegbwzzyjps635.jpeg?q=70",
        title: "Deadpool",
        language: "Hindi",
        cost: 325,
    },
    {
        id: 6,
        image: "https://rukminim2.flixcart.com/image/612/612/xif0q/movie/e/i/f/2012-dvd-soni-hindi-the-adventures-of-tintin-the-secret-of-the-original-imagqbtvtakrzg8f.jpeg?q=70",
        title: "THE ADVENTURES OF TINTIN",
        language: "Hindi",
        cost: 200,
    },
    {
        id: 7,
        image: "https://rukminim2.flixcart.com/image/612/612/av-media/movies/e/t/y/harry-potter-and-the-deathly-hallows-part-1-original-imae25gzc6ayzfaz.jpeg?q=70",
        title: " Harry Potter And The Deathly Hallow",
        language: "Hindi",
        cost: 600,
    },
    {
        id: 8,
        image: "https://rukminim2.flixcart.com/image/612/612/av-media/movies/2/g/w/gangs-of-wasseypur-i-ii-original-imadnzhpajzajcah.jpeg?q=70",
        title: " Gangs Of Wasseypur I - II",
        language: "Hindi",
        cost: 875,
    },
    {
        id: 9,
        image: "https://rukminim2.flixcart.com/image/612/612/jeokbrk0/movie/z/6/2/2009-dvd-excel-home-videos-english-avatar-original-imaf3bd6zed7phes.jpeg?q=70",
        title: " Avatar",
        language: "Hindi",
        cost: 545,
    },
    {
        id: 10,
        image: "https://rukminim2.flixcart.com/image/612/612/movie/z/v/4/deadpool-2016-english-dvd-excel-home-videos-original-imaegbwzzyjps635.jpeg?q=70",
        title: "Deadpool",
        language: "Hindi",
        cost: 325,
    },
    {
        id: 11,
        image: "https://rukminim2.flixcart.com/image/612/612/av-media/movies/e/t/y/harry-potter-and-the-deathly-hallows-part-1-original-imae25gzc6ayzfaz.jpeg?q=70",
        title: " Harry Potter And The Deathly Hallows",
        language: "Hindi",
        cost: 600,
    },
    {
        id: 12,
        image: "https://rukminim2.flixcart.com/image/612/612/av-media/movies/e/n/c/dhoom-3-original-imadvw2ypnsm38at.jpeg?q=70",
        title:"Dhoom:3",
        language: "Hindi",
        cost: 400,
    },
];
export default movies;